build:apk:
  image: registry.git.callpipe.com/linphone/build-infrastructure/android-builder:latest
  before_script:
    - echo "${APK_SIGNING_KEYSTORE}" | base64 -d > app/keystore.jks
    - echo -e "storePassword=${ANDROID_KEYSTORE_PASSWORD}\nkeyPassword=${ANDROID_KEYSTORE_KEY_PASSWORD}\nkeyAlias=${ANDROID_KEYSTORE_KEY_ALIAS}\nstoreFile=keystore.jks" > keystore.properties
    - echo "${GOOGLE_SERVICES_JSON}" > app/google-services.json
  script:
    - gradle assembleRelease
    - cp app/build/outputs/apk/release/*.apk .
  artifacts:
    paths:
      - "*.apk"
    expire_in: 1 week
  except:
    - triggers

git sync:
  image: debian:latest
  before_script:
    - apt-get update && apt-get install -y git
  script:
    - git remote set-url origin "https://${GITLAB_PUSH_CREDENTIALS}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git remote add github https://github.com/AccelerateNetworks/linphone-android
    - git checkout "${BRANCH}" || git checkout -b "${BRANCH}"
    - git pull github "${BRANCH}"
    - git push origin "${BRANCH}"
  only:
    - triggers
    - schedules
    - web