job-android:

  stage: build
  tags: [ "docker-android" ]
  image: gitlab.linphone.org:4567/bc/public/linphone-android/bc-dev-android:20230414_bullseye_jdk_17_cleaned

  before_script:
    - if ! [ -z ${SCP_PRIVATE_KEY+x} ]; then eval $(ssh-agent -s); fi
    - if ! [ -z ${SCP_PRIVATE_KEY+x} ]; then echo "$SCP_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null; fi
    - if ! [ -z ${ANDROID_SETTINGS_GRADLE+x} ]; then echo "$ANDROID_SETTINGS_GRADLE" > settings.gradle; fi
    - git config --global --add safe.directory /builds/BC/public/linphone-android

  script:
    - ./gradlew app:dependencies | grep org.linphone
    - ./gradlew assembleDebug

  artifacts:
    paths:
      - ./app/build/outputs/apk/debug/app-debug.apk
    when: always
    expire_in: 1 week


.scheduled-job-android:
  extends: job-android
  only:
    - schedules
