name: sync to gitlab
on:
  push:
    branches: [ master ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: tell gitlab to pull
        run: curl -sd "TOKEN=${{ secrets.GITLAB_TOKEN }}" -d "variables[BRANCH]=${GITHUB_REF#refs/heads/}" https://git.callpipe.com/api/v4/projects/371/trigger/pipeline